# Generated by Django 4.1.4 on 2023-01-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('deptno', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trainers')),
            ],
        ),
    ]
